[project]
name = "dlt-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt[duckdb,parquet]>=1.9.0",
    "parquet>=1.3.1",
    "streamlit>=1.44.0",
]
